// C:\Users\saran\sb-vr-5\models\achievement.js

const mongoose = require('mongoose');

const achievementSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    projectId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Project',
        required: true
    },
    pointsEarned: {
        type: Number,
        required: true,
        default: 0
    },
    aiFeedback: {
        type: String, // Feedback generated by the AI on project completion
        default: 'No feedback provided'
    },
    dateAwarded: {
        type: Date,
        default: Date.now
    }
});

const Achievement = mongoose.model('Achievement', achievementSchema);

module.exports = Achievement;
